### ISSUE TITLE
没有去掉引号

### ISSUE THREAD

**Issue by Hongchenglong** [TieJiang13/Homework#2]
**Describe the bug**
输入 `看看 “字符串”` 时，输出没有去掉引号。

**Comment by TieJiang13** [comment]
宝贵建议，已采纳，正在思考如何修改

**Comment by TieJiang13** [comment]
已解决
![image](https://user-images.githubusercontent.com/52875154/74215214-4ce75800-4cdb-11ea-8bae-9fbfeee516f3.png)
